### ISSUE TITLE
chatgpt.exceptions.ForbiddenException: Access forbidden.

### ISSUE THREAD

**Issue by Shuangcheng-Ni** [mbroton/chatgpt-api#18]
chatgpt-api version: 0.2.1<br>
My code:
```
with ChatGPT(session_token='...', response_timeout=30) as chatter:
    ask = input('ask:')
    print('ans:', chatter.send_message(ask).content)
```
The exception it causes:
```
Traceback (most recent call last):
    File "...", line ..., in <module>
        with ChatGPT(session_token='...', response_timeout=30) as chatter:
    File "/home/user/.local/lib/python3.8/site-packages/chatgpt/api.py", line 68, in __enter__
        self.authenticate()
    File "/home/user/.local/lib/python3.8/site-packages/chatgpt/api.py", line 81, in authenticate
        raise ForbiddenException(
chatgpt.exceptions.ForbiddenException: Access forbidden. It may indicate that something had changed on ChatGPT side. See https://github.com/mbroton/chatgpt-api/issues
```
It seems that the chatgpt server has upgraded its security policy, which might cause authentication failure.

**Comment by bensmrs** [comment]
Yup, they put a Cloudflare anti-DDOS frontend. I think we have to resort to Selenium-like trickeries to be able to bypass it…

**Comment by danielthedank** [comment]
Good luck. Needles to say a command line chatGPT is a game changer. *Salute*

**Comment by mbroton** [comment]
I'm aware of this problem. I'll try to make it work in a day or so.

**Comment by mbroton** [comment]
I made it works, but I need to test it and adapt to the CLI.
Unfortunately, ChatGPT is currently overloaded, so I have to pause my work.

**Comment by mbroton** [comment]
My changes from yesterday don't work anymore.
It's really time consuming to keep it up to date with OpenAI's changes and I can't afford it.
I'm thinking about archiving the repository.
If someone wants to contribute or start working on this project, feel free to do so.

**Comment by Shuangcheng-Ni** [comment]
> My changes from yesterday don't work anymore. It's really time consuming to keep it up to date with OpenAI's changes and I can't afford it. I'm thinking about archiving the repository. If someone wants to contribute or start working on this project, feel free to do so.

I've found a [repository](https://github.com/mmabrouk/chatgpt-wrapper) that still works. It resorts to playwright trickeries to bypass the Cloudflare frontend. Maybe you can refer to it.
