### ISSUE TITLE
Error, when use "chatgpt setup" or "chatgpt start"

### ISSUE THREAD

**Issue by Mideks** [mbroton/chatgpt-api#22]
Command:
```
chatgpt setup
```
Error:
```
Traceback (most recent call last):
  File "c:\users\lenovo\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\lenovo\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python39\Scripts\chatgpt.exe\__main__.py", line 4, in <module>
  File "c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages\chatgpt\__init__.py", line 1, in <module>
    from . import api
  File "c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages\chatgpt\api.py", line 11, in <module>
    from chatgpt import payloads
  File "c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages\chatgpt\payloads.py", line 5, in <module>
    message: str, id_: str, conv_id: str | None, parent_msg_id: str | None
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

**Comment by mbroton** [comment]
Hi! Thanks for reporting this issue.
Check the [current status](https://github.com/mbroton/chatgpt-api#status) of the project.
Currently it's not working since ChatGPT introduced cloudflare protection and I don't have a time to fix it.

**Comment by Mideks** [comment]
> Hi! Thanks for reporting this issue.
> Check the [current status](https://github.com/mbroton/chatgpt-api#status) of the project.
> Currently it's not working since ChatGPT introduced cloudflare protection and I don't have a time to fix it.

Oh, then I'm sorry. well, thank you for your time:) I hope that the api will soon be released.
